### ISSUE TITLE
Adding ExpertGate

### ISSUE THREAD

**Issue by niniack** [ContinualAI/avalanche#1023] opened 2022-05-12 12:46 UTC
I'm interested in adding ExpertGate to Avalanche. A few questions/thoughts I wanted to clarify before moving forward:

  - While the original ExpertGate model uses a pretrained AlexNet, this limits the ExpertGate to whatever task PyTorch's AlexNet was pretrained for (I think its vision tasks?). Should this implementation allow one to feed whichever model they'd like? Or, am I grossly misunderstanding something here?
  - I imagine ExpertGate would be implemented as a `Model`? I can also view it as a `Strategy` where you feed in your choice of model (see point above). Although, my gut says its should be a `Model`.

**Comment by AntonioCarta** [comment] 2022-05-12 13:34
1) I agree. I would define a general component and leave AlexNet as the default. Keep in mind that we have the [CL Baselines](github.com/continualAI/continual-learning-baselines/) repo to host reproducible experiments.

2) You can check how we implement [Progressive Neural Networks](https://avalanche-api.continualai.org/en/v0.1.0/generated/avalanche.models.PNN.html?highlight=pnn#avalanche.models.PNN) in Avalanche. Basically, we have a simple API to define [dynamic modules](https://avalanche-api.continualai.org/en/v0.1.0/models.html#dynamic-modules) that are expanded over time. Then, the ExpertGate strategy will be Naive strategy + an ExpertGate model.

**Comment by AntonioCarta** [comment] 2022-05-12 13:34
I'm assigning this to you. Thanks for the help!

**Comment by niniack** [comment] 2022-06-04 06:22
Reflecting on the first draft of the implementation, there are a couple of things I think I'm missing and wanted to pick your (anyone's) brain about: 

- What triggers the change in the optimizer's parameters? I don't think the optimizer is updating its parameters and I know I don't have to manually do it (at least according to the documentation)
- What is the major difference between the `model_adaptation` method and the `before_training_exp` method. I imagine the former triggers something else (perhaps parameter updates for optimizer?)

**Comment by AndreaCossu** [comment] 2022-06-04 09:40
1. The optimizer is automatically reset after each experience in the `Supervised` template (avalanche/training/templates/supervised.py). You can check the `make_optimizer` method in the supervised template. In this way, if your model expands/changes its parameters after each experience, the change is taken into consideration by the newly created optimizer. This happens because `model_adaptation` is called *before* `make_optimizer` in the `base_sgd` template from which the `supervised` template inherits.
2. The `before_training_exp` is simply a callback that allows to execute some code before training on each experience. `model_adaptation` allows to dynamically modifies the model and in the `base_sgd` template it is called after each experience. The default version of this method simply calls the `adaptation` method of the model, if defined. This way, you can build custom models which do custom things during adaptation. One example is the multi head: on `adaptation` call the model instantiates a new head for the incoming task.

Let me know if the interplay between the `base_sgd` and `supervised` templates is not clear or if you need further help in understanding what `model_adaptation` and `make_optimizer` do.

**Comment by niniack** [comment] 2022-06-16 09:59
Thanks, 

1. I got a chance to look at the source file and I see where the optimizer get's updated! 
2. I see, thanks for the clarification

After I wrote my initial questions, I did some more documentation + source code digging and cleared up some of the doubts. Your comments + my reading helped me figure it out!

**Closed** 2023-05-29 08:55 UTC
Labels: Feature - Medium Priority, Training, models
