### ISSUE TITLE
Integrating the CtRL Benchmark 

### ISSUE THREAD

**Issue by ludc** [ContinualAI/avalanche#377] opened 2021-03-10 18:25 UTC
Hi,

 We will work to integrate the CtRL benchmark in avalanche in the next weeks. 

 https://arxiv.org/pdf/2012.12631.pdf

 I willl keep you in touch

**Comment by TomVeniat** [comment] 2021-04-17 23:31
Hi there,
I'd like to have your opinion on my stab at this integration before going further, if that's okay with you.
Since we are using a *task-level* cross-validation in the CTrL benchmark, each task comes with its own train, validation, and test sets.
To my understanding, the recent modifications to the `GenericCLScenario` (#516 ) allow that kind of scenario if we do something like:
```python
streams = GenericCLScenario(
            stream_definitions={
                'train': ([task_1_train, task_2_train, ...],),
                'validation': ([task_1_val, task_2_val, ...],),
                'test': ([task_1_test, task_2_test, ...],),
            }
```
where each `task_x_y` is an `AvalancheTensorDataset` containing the appropriate data.

The learner would then go through the three streams in parallel to have access to the different splits for each task at the same time. I understand that the intended usage is to have several independent streams, with some test tasks and potentially validation tasks, but it seems to work quite well that way as well.

Is it a correct way of using the `GenericCLScenario` or is it hacky and there is a better way?

**Comment by vlomonaco** [comment] 2021-04-19 18:54
@lrzpellegrini can you please guide @TomVeniat on this? Also in light of your recent PR #545?

**Comment by lrzpellegrini** [comment] 2021-04-20 13:34
Hi @TomVeniat, the way you use `GenericCLScenario` seems good to me. I recommend waiting for #545 to be integrated before continuing (will probably be merged today) as that PR contains the implementation for the updated helper functions.

However, consider that helpers like `dataset_benchmark` will still wrap `GenericCLScenario`, so it's ok if you decide to use `GenericCLScenario` directly.

If you already have some draft code for CtRL feel free to share it with us. You can also open a draft PR if you want!

**Comment by lrzpellegrini** [comment] 2021-04-21 13:55
Hi @TomVeniat, PR #545 is now integrated in Avalanche. Consider giving a look at `dataset_benchmark`. Has nearly the same interface as `GenericCLScenario`, but should be more stable w.r.t. future changes in the API.

Let me know if I can help you with this!

**Comment by TomVeniat** [comment] 2021-04-23 15:18
Hi @lrzpellegrini,
Thanks for your advice, I replaced `GenericCLScenario` with `dataset_benchmark` without issues.
However, I have a problem with the transforms associated with each task.
If I understand correctly, `dataset_benchmark` can take transforms through `train_transform`, `eval_transform` and `other_streams_transforms`. The problem is that these transforms will be applied to the whole stream while I'd like to provide one transform per task since they all have different input distributions.
For example, the `norm` variable in #561 contains the list of the normalizations that need to be applied to each task. Is there a way to provide task-level transforms ?

**Comment by lrzpellegrini** [comment] 2021-04-23 15:32
Yes, absolutely! It should be sufficient to equip every `AvalancheDataset` with its own transformation

**Closed** 2022-01-03 13:54 UTC
Labels: Feature - Medium Priority, Benchmarks
