### ISSUE TITLE
AGEM: Dataloader Exception RuntimeError: DataLoader worker (pid(s) 17081, 17084, 17087, 17090) exited unexpectedly

### ISSUE THREAD

**Issue by DannyFGitHub** [ContinualAI/avalanche#841] opened 2021-11-29 15:02 UTC
🐛 **Describe the bug**
When training the dataloader on experience 2 out of 3 the DataLoader triggers an exception, I'm unsure whats causing it.
It only happens so far with the AGEM strategy.

🐜 **To Reproduce**
Steps / minimal snipped of code to reproduce the issue.
- Using NI_Benchmark from ImageFolder
- AGEM strategy on a MobileNet3 model

🐝 **Expected behavior**
Expected training to complete and for Dataloader not to show the exception.

🦋 **Additional context**

Full Exception stacktrace:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
TypeError: __init__() missing 1 required positional argument: 'avalanche_dataset'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
TypeError: __init__() missing 1 required positional argument: 'avalanche_dataset'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
TypeError: __init__() missing 1 required positional argument: 'avalanche_dataset'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
TypeError: __init__() missing 1 required positional argument: 'avalanche_dataset'
Traceback (most recent call last):
  File "/Users/<Username>/Desktop/avalanche-project/env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 990, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/queues.py", line 113, in get
    if not self._poll(timeout):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 262, in poll
    return self._poll(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 429, in _poll
    r = wait([self], timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 936, in wait
    ready = selector.select(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
  File "/Users/<Username>/Desktop/avalanche-project/env/lib/python3.9/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 17087) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/<Username>/Desktop/avalanche-project/model_making/covid_xray_training.py", line 503, in <module>
    train_model(datasource.train_data_dir, datasource.test_data_dir, base_model,
  File "/Users/<Username>/Desktop/avalanche-project/model_making/covid_xray_training.py", line 428, in train_model
    model_wrapped_in_strategy.train(experiences=experience)
  File "/Users/<Username>/Desktop/avalanche-project/env/lib/python3.9/site-packages/avalanche/training/strategies/base_strategy.py", line 276, in train
    self.train_exp(self.experience, eval_streams, **kwargs)
  File "/Users/<Username>/Desktop/avalanche-project/env/lib/python3.9/site-packages/avalanche/training/strategies/base_strategy.py", line 324, in train_exp
    self.training_epoch(**kwargs)
  File "/Users/<Username>/Desktop/avalanche-project/env/lib/python3.9/site-packages/avalanche/training/strategies/base_strategy.py", line 494, in training_epoch
    self._before_training_iteration(**kwargs)
  File "/Users/<Username>/Desktop/avalanche-project/env/lib/python3.9/site-packages/avalanche/training/strategies/base_strategy.py", line 538, in _before_training_iteration
    p.before_training_iteration(self, **kwargs)
  File "/Users/<Username>/Desktop/avalanche-project/env/lib/python3.9/site-packages/avalanche/training/plugins/agem.py", line 47, in before_training_iteration
    mb = self.sample_from_memory()
  File "/Users/<Username>/Desktop/avalanche-project/env/lib/python3.9/site-packages/avalanche/training/plugins/agem.py", line 100, in sample_from_memory
    return next(self.buffer_dliter)
  File "/Users/<Username>/Desktop/avalanche-project/env/lib/python3.9/site-packages/avalanche/benchmarks/utils/data_loader.py", line 208, in __iter__
    batch = next(t_loader)
  File "/Users/<Username>/Desktop/avalanche-project/env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/Users/<Username>/Desktop/avalanche-project/env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "/Users/<Username>/Desktop/avalanche-project/env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1152, in _get_data
    success, data = self._try_get_data()
  File "/Users/<Username>/Desktop/avalanche-project/env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1003, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 17081, 17084, 17087, 17090) exited unexpectedly

**Comment by AntonioCarta** [comment] 2021-11-29 16:19
This may be an out-of-memory error. We have to look if we are keeping in memory something that we can move to the CPU. Otherwise, I think the only thing you can do is to reduce the batch size.

**Comment by AntonioCarta** [comment] 2022-03-28 09:17
#951 should fix this. I'm closing the issue for the moment. Feel free to reopen it if the problem is still there.

**Closed by AntonioCarta** 2022-03-28 09:17 UTC
Labels: bug, Training
