### ISSUE TITLE
JointTraining strategy does not shuffle the whole dataset when picking minibatch

### ISSUE THREAD

**Issue by ema-marconato** [ContinualAI/avalanche#1094] opened 2022-07-15 14:10 UTC
So I noticed that when calling JointTraining on a `dataset_benchmark` the mini-batches are not iid w.r.t. the whole datasets. Any clue on how to solve the issue?

**Comment by AndreaCossu** [comment] 2022-07-17 13:31
From a quick look at the code I think the mini-batches should be shuffled since `shuffle=True` by default in the dataloader creation. Can you please provide a quick script to verify your results? I can start from there and help you out :smile:

**Comment by AntonioCarta** [comment] 2023-02-20 13:08
closing this since it doesn't look like an avalanche bug and we cannot reproduce it.

**Closed by AntonioCarta** 2023-02-20 13:08 UTC
Labels: bug
