### ISSUE TITLE
Make CoPE example data incremental

### ISSUE THREAD

**Issue by Mattdl** [ContinualAI/avalanche#616] opened 2021-05-17 13:47 UTC
Putting the new data-incremental interface to use for the CoPE example, which is now still class incremental.
Can someone assign this issue to me? Thanks!

**Comment by Mattdl** [comment] 2021-05-18 13:51
I get an error when implementing the data incremental loader.

    -- >> Start of training phase << --
    -- Starting training on experience 242 (Task 0) from train stream --
    
    [...] RecursionError: maximum recursion depth exceeded while calling a Python object

Should I make a PR to have a working example?

**Comment by vlomonaco** [comment] 2021-05-18 13:57
Yes so that we can provide help in case you need it!

**Comment by Mattdl** [comment] 2021-05-19 08:46
I've added the PR to reproduce the error. See #543 which had the same error.
@lrzpellegrini you found a fix for #543, do you have an idea what may cause the error in this case?

**Comment by lrzpellegrini** [comment] 2021-05-24 12:40
Hi @Mattdl, sorry for the delay. I reproduced the bug on the cope example of your fork. The recursion bug is very similar to the one I previously fixed, but this seems to be linked to a different corner case. I'll fix it asap.

**Comment by lrzpellegrini** [comment] 2021-05-24 16:44
The last PR should fix the recursion issue and it will be merged soon. Let me know if it works!

**Comment by Mattdl** [comment] 2021-05-26 15:10
Hi thanks for the effort! The recursion bug seemed to be solved, but now after 201 iterations another problem in the corner case arises. It seems to happen when concatting for the replay buffer, i.e. in AvalancheConcatDataset.
This is the stack trace, it should be an index out of range exception:

    Traceback (most recent call last):
      File .../avalanche/training/plugins/cope.py", line 88, in before_training_exp
        AvalancheConcatDataset(self.replay_mem.values()),
      File .../avalanche/benchmarks/utils/avalanche_dataset.py", line 1616, in __init__
        super().__init__(ClassificationDataset(),  # not used
      File .../avalanche/benchmarks/utils/avalanche_dataset.py", line 306, in __init__
        self._flatten_dataset()
      File .../avalanche/benchmarks/utils/avalanche_dataset.py", line 1849, in _flatten_dataset
        flattened_list += self._flatten_subset_concat_branch(dataset)
      File .../avalanche/benchmarks/utils/avalanche_dataset.py", line 1904, in _flatten_subset_concat_branch
        last_c_targets.append(dataset.targets[idx])
    IndexError: list index out of range

I'll make another PR to make it reproducable.

**Comment by Mattdl** [comment] 2021-06-03 11:53
The issue seemed to be solved. However, the training time has a huge increase compared to the class-incremental setup.
Split-MNIST now takes about 6hours to complete a single epoch, compared to usually 10min on my setup. (About factor 40 slowdown, which makes it infeasible when going to larger setups)

Should I make another Issue for this separately?

**Comment by lrzpellegrini** [comment] 2021-06-03 13:33
Yes, I think it's better to create a separate issue for this.

Do you have a log of how the running time is split across the various procedures (replay update, training, etc.)?

**Closed** 2021-11-04 15:46 UTC
Labels: Benchmarks, Training
