### ISSUE TITLE
Stack error on using mini-batch size > 1

### ISSUE THREAD

**Issue by hiteshK03** [ContinualAI/avalanche#506] opened 2021-04-07 20:32 UTC
**Describe the bug**
On running the below code:
```
cl_strategy = EWC(
    model_ft, optimizer_ft, criterion, ewc_lambda=5,
    train_mb_size=32, train_epochs=4, eval_mb_size=32
)
```
We get the below-mentioned error. This works fine for train_mb_size=1 and eval_mb_size=1 but gives error for any other value.
```
/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py in default_collate(batch)
     53             storage = elem.storage()._new_shared(numel)
     54             out = elem.new(storage)
---> 55         return torch.stack(batch, 0, out=out)
     56     elif elem_type.__module__ == 'numpy' and elem_type.__name__ != 'str_' \
     57             and elem_type.__name__ != 'string_':

RuntimeError: stack expects each tensor to be equal size, but got [3, 341, 500] at entry 0 and [3, 313, 500] at entry 1
```
**To Reproduce**
```
cl_strategy = EWC(
    model_ft, optimizer_ft, criterion, ewc_lambda=5,
    train_mb_size=32, train_epochs=4, eval_mb_size=32
)
```
**Expected behavior**
It was supposed to train with the specified mini-batch size.

**Comment by AndreaCossu** [comment] 2021-04-08 07:04
Hi @hiteshK03 ! Thank you for reaching out. 
Given your traceback, the error does not seem to be related to EWC, but rather to the dataloading. On which scenario are you training on? Can you share a minimal working example that we can directly run?

**Comment by hiteshK03** [comment] 2021-04-08 11:15
Yes, it is related to dataloading, sorry for not mentioning it clearly before.
I have also opened a PR request for fixing an error in the reading of images. (where it takes the last newline character also into account in the filename)
After fixing that only, I could move forward to the dataloading part.
This is the following code and I'm training on Incremental Class scenario.
```
dir = '/content/drive/MyDrive/RND_2021/CUB'
model_ft = models.resnet18(pretrained=True)
optimizer_ft = optim.SGD(model_ft.parameters(), lr=0.001, momentum=0.9)
criterion = nn.CrossEntropyLoss()

clscenario = SplitCUB200(dir, n_experiences=10, classes_first_batch=20,return_task_id=True, shuffle=True)
cl_strategy = EWC(
    model_ft, optimizer_ft, criterion, ewc_lambda=5,
    train_mb_size=32, train_epochs=50, eval_mb_size=32
)
print('Starting experiment...')
results = []
for experience in clscenario.train_stream:
    print("Start of experience: ", experience.current_experience)
    print("Current Classes: ", experience.classes_in_this_experience)

    cl_strategy.train(experience)
    print('Training completed')

    print('Computing accuracy on the whole test set')
    results.append(cl_strategy.eval(clscenario.test_stream))
```

**Comment by vlomonaco** [comment] 2021-04-08 18:22
Ok first problem fixed in #505, let us know if this one persists!

**Comment by hiteshK03** [comment] 2021-04-09 19:28
Yes, this problem is still there

**Comment by AndreaCossu** [comment] 2021-04-12 09:27
I inspected the CUB200 dataset and the problem is related to the fact that each pattern is a 3-channel image with different height and width. So, each pattern tensors has shape (3, H, W). The dataloader tries to build the minibatch with `stack` and fails since dimensions are different.  
I think this could be fixed by forcing a center crop of same dimensions on all patterns or by padding. However, I don't know if there are standard practices to work with this dataset. @lrzpellegrini , @vlomonaco do you have any hints on this?

**Comment by vlomonaco** [comment] 2021-04-12 09:45
I suggest to look in a recent CL paper using this dataset we can use as a reference! In the meanwhile I think you can center-crop to a fixed size just to solve this bug!

**Comment by lrzpellegrini** [comment] 2021-04-12 12:28
It seems to me that the current implementation of the CUB200 dataset [here](https://github.com/ContinualAI/avalanche/blob/master/avalanche/benchmarks/datasets/cub200/cub200.py) doesn't consider the bounding boxes found in the annotations file.

Bounding boxes have been used to extract images for classification tasks in various papers (see https://arxiv.org/pdf/1903.08362.pdf or https://arxiv.org/pdf/1802.02950.pdf). These crops are then resized (usually 224x224).

Am I missing something?

**Comment by AndreaCossu** [comment] 2021-04-12 14:02
I think we should be fine after implementing bounding boxes + cropping

**Comment by lrzpellegrini** [comment] 2021-04-12 14:59
Ok, I'll try to check if a sproper implementation of the dataset exists in the wild ;)

**Closed** 2021-04-12 18:03 UTC
Labels: Benchmarks, bug
